### PR TITLE
Add controller Support (and a few other changes)

### PR DESCRIPTION
**Pull request by ShadowKitty42**
Once I started getting into it, I noticed some other things to change, in addition to my goal of adding controller support. I hope that's alright :)
Here's the changelog I made while making my edits:

Improve Gamepad Support
 - Pressing A functions like the mouse left click, in conjunction with cursor location. "Clicking" outside the window works the same for controller and mouse.
 - Pressing B closes the window, just like any other menu in-game.
 - Window scrolls correctly with right thumbstick, using scroll amount in config.

Fix scrolling inconsistency - Mouse wheel didn't scroll by the configured value
Combined Mouse Left click with the equivalent controller button, so future controller support is easily maintained.
Make up/down arrow sprites functional (I don't know how to animate them like in the other game menus.)

### CODE REVIEW

**Comment by Pathoschild** [comment]
Looks like this got merged into #35.

**Comment by ShadowKitty42** [comment]
Yeah, wasn't my intention. I've literally never worked with someone else using Git or GitHub, so I'm just stumbling through it a bit.

**Comment by ShadowKitty42** [comment]
I actually did a bit of research earlier, and now I know that I should put each feature in its own branch, so that I can do separate pull requests.

**Comment by Pathoschild** [comment]
If you're willing, please do break your one pull request into separate pull requests. It's easier to review, discuss, and merge them that way. It also means I can review a small pull request when I have a bit of spare time, instead of waiting until I have more time to look into a combined set of changes. :)

The easiest way to do that would be to branch from the current `develop`, cherry-pick each change into the right branch, and submit a pull request for each branch.

**Pull request closed without merging**
