### PR TITLE
fixed NullReferenceException (#201)

### PR DESCRIPTION
**Pull request by f4iTh**
Tested with and without a tractor: No NullReferenceException on my side

### CODE REVIEW

**Comment by Pathoschild** [comment]
@f4iTh Is the tractor still removed from the social menu? I think `e.NewMenu is SocialPage` will always be false, since the menu itself is `GameMenu`.

**Comment by f4iTh** [comment]
@Pathoschild Yes, it's still removed from the social menu. It doesn't show up in the social menu for me
EDIT: Wait actually no. One moment, please.

**Comment by f4iTh** [comment]
_We good?_

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming Tractor Mod 4.4.1. Thanks!

**Pull request merged**
