### PR TITLE
[Fast Animations] Add Open Chest Handler

### PR DESCRIPTION
**Pull request by weizinai**
Speed up the chest-open animation.

### CODE REVIEW

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming Fast Animations 1.12.0. Thanks again for the help!

**Comment by Pathoschild** [comment]
@weizinai One player reports that this sometimes breaks chest opening in multiplayer. See the [comments on the Fast Animations page](https://www.nexusmods.com/stardewvalley/mods/1089/?tab=posts&jump_to_comment=138672758):
> 有时，新版本在本地在线播放时无法打开盒子。您可以听到盒子打开的声音，但没有盒子页面。在旧版本中不会出现此问题。
> [...]
> 我发现了问题。这是由1.12.0版本的新打开宝箱加速动画引起的。在常规的单人游戏中，问题不会出现。但是，在线玩游戏时，问题发生了，我经常打不开箱子。要解决这个问题，您可以尝试稍微放慢宝箱动画速度。到目前为止，SMAPI 尚未报告任何错误。

Do you know off-hand why that might happen? I can look into it if not.

**Comment by weizinai** [comment]
I'm so sorry. I don't know why. I don't know much about the online aspect of Stardew Valley.

**Comment by Pathoschild** [comment]
No worries! I found the fix for it, so that's in the upcoming Fast Animations 1.12.1.

**Pull request merged**
