### PR TITLE
Suppress keybinds for use with binding to Controller Buttons

### PR DESCRIPTION
**Pull request by Deflaktor**
Added Suppress Keybind for:
- Lookup Anything Hotkeys
- Horse Flute Hotkey

This allows setting these Hotkeys to a DPad direction or the RightStick without making the character move or opening the chat window

### CODE REVIEW

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Thanks! Merged into `develop` for the upcoming Horse Flute Anywhere 1.1.8 and Lookup Anything 1.35.2.

**Review by Deflaktor — COMMENTED** [review]
Hm, if it only surpresses when it applies it does not cover my use case.
i have a xbox controller and would like to map the flute to dpaddown since I dont use the dpad at all. But if it only surpresses when it applies, then i walk down when pressing the dpaddown instead of getting the error message that I dont have the flute. If I override the dpaddown I dont want it to retain its old function at all.

**Comment by Deflaktor** [comment]
So, could you revert 7761e62 ?

**Comment by Pathoschild** [comment]
`CanPlayFlute` doesn't check whether the flute will work, only if you _could_ play it in the current context. So it won't suppress the keybind if you're not holding a flute at all (in balanced mode) or in a cutscene for example; but it _will_ suppress it if trying to play the flute shows an error (e.g. not enough space to summon a horse).

**Comment by Deflaktor** [comment]
So I understand correctly, that if I don't have the flute in balanced mode, I can still use dpaddown to move downwards? I think it's weird that the button changes its behavior depending on whether I do own the flute or not.

**Comment by Pathoschild** [comment]
Yep. Only suppressing input when the mod handles it is the usual convention in Stardew Valley modding, since there's many different contexts where input can be handled. If you want to always force-suppress a keybind, you could maybe create a simple mod which just has a list of keybinds in its `config.json` that it always suppresses.

**Comment by Deflaktor** [comment]
I see. I guess in certain contexts it makes sense to follow that convention. 
I already tried making a tiny mod using a configurable list of keys to be surpressed. However, contrary to what the modding wiki says, it also prevents mods from handling the input. This is what brought me to make this PR in the first place.

**Comment by Deflaktor** [comment]
Nvm, I was indeed able to make that simple mod for suppressing keys after taking a second look and soon after I found out about [EventPriority]
Turns out my mod was handling the suppress key stuff before the horse flute mod and as such it prevented it from firing. 

I now added a ButtonsChanged event with [EventPriority(EventPriority.Low - 10000)] so that it suppresses the key after all other mods may have handled it. This solves my use case.

Thanks for pointing me into the right direction!

**Pull request merged**
