### PR TITLE
Fix Chest Anywhere mod for Android platform

### PR DESCRIPTION
**Pull request by ZaneYork**

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks! I'm testing this with an Android player. It seems auto-grabbers and chests work, but the shipping bin isn't working:
> image

**Comment by ZaneYork** [comment]
Already known this issue, shippingbin is partly supported, which can recall items from it, but can't put items into it,due to the extra logic of android version.
Which means, we should add game patch or create a custom chest menu to fix this.

**Comment by ZaneYork** [comment]
Here is the solution for make shipping bin can ship items, but recall function was broken.
The render logic or update logic must rewrtie to fix the issue.
Or else we can use a inventory menu to finish this work, by detect every state change.



                menu.initializeShippingBin();

                //ClickableTextureComponent textureComponent = (ClickableTextureComponent)typeof(ItemGrabMenu).GetField("lastShippedHolder", BindingFlags.Public | BindingFlags.Instance).GetValue(menu);

                //textureComponent.bounds = new Rectangle(-100, -100, 96, 96);

**Comment by ZaneYork** [comment]
Fix done, by using the organize button.

**Comment by vidhitchauhann** [comment]
Where to use this mod?

**Comment by ZaneYork** [comment]
> Where to use this mod?

[Here ](https://drive.google.com/open?id=1P9yR_9JPYUhFEdtHJW36nCS8fsTcj3wb)is the unofficial 
 version.

**Comment by vidhitchauhann** [comment]
Thankyou Zane!!
Is there any ui info mod available for android right now?

**Comment by ZaneYork** [comment]
> Thankyou Zane!!
> Is there any ui info mod available for android right now?

Also at my [GDrive](https://drive.google.com/open?id=1C2pQe75oEdyeGoQ4yh0Aow5FixhtAwsK), in unofficial mods folder.

**Comment by Pathoschild** [comment]
Thanks for the help! I'm going to get SMAPI 3.3 released, then add this in the next Chests Anywhere update.

**Comment by ZaneYork** [comment]
Supports textbox on Android now! Chest rename can works properly

**Comment by Pathoschild** [comment]
Update: the next Chests Anywhere update depends on SMAPI 3.3, so I'm currently waiting for SMAPI 3.3 to release on Android so we can test the changes.

**Comment by ZaneYork** [comment]
> Update: the next Chests Anywhere update depends on SMAPI 3.3, so I'm currently waiting for SMAPI 3.3 to release on Android so we can test the changes.

Here is my [release](https://github.com/ZaneYork/SMAPI-Android-Installer/releases), which already upgrade to SMAPI 3.3.2

**Comment by Pathoschild** [comment]
@ZaneYork Thanks! I'm having trouble finding Android testers. I changed the shipping bin logic (so you have separate shipping bin entries instead of a hidden toggle feature) and added a few optimizations. If this version works fine for you, I'll merge it in and release it.

* [ChestsAnywhere 1.18.0-alpha.20200307.zip](https://github.com/Pathoschild/StardewMods/files/4302676/ChestsAnywhere_1.18.0-alpha.20200307.zip)

**Comment by ZaneYork** [comment]
It can't work, nothing happened when I click the Virtual Button B and no error was output(did it surrounded by try catch?), here is the [error log](https://smapi.io/log/e710832b1c674a8e9e697be322a4eb1f)

**Comment by ZaneYork** [comment]
> It can't work, nothing happened when I click the Virtual Button B and no error was output(did it surrounded by try catch?), here is the [error log](https://smapi.io/log/e710832b1c674a8e9e697be322a4eb1f)

It works with hardware key, I modified activite key to VolumeUp, it works(May be a bug of VirtualKeyboard?)

**Comment by ZaneYork** [comment]
Caught the bug, this method JustPressedUnique.The VirtualKeyboard release a new KeyPresssed event during the event process chain.Which means, ChestAnywhere had handled a KeyPressed event( with mouse button pressed), and mark LastUniqueTick to latest tick, and refuse any event later.

**Comment by Pathoschild** [comment]
Yep, ideally Virtual Keyboard should change SMAPI's key state instead of raising a custom event. I'll add a change in SMAPI to make that possible.

**Comment by ZaneYork** [comment]
Another feedback, shipping bin retrieve items mode did not works properly.It just looks exactly same as ship item mode,and can't change to the ship mode(maybe did the same thing).

**Comment by Pathoschild** [comment]
I rebased your branch to remove the merge commits and update to the latest code; do you mind if I force-push to your branch so you can see the current code?

**Comment by ZaneYork** [comment]
> I rebased your branch to remove the merge commits and update to the latest code; do you mind if I force-push to your branch so you can see the current code?

Never mind, just do it

**Comment by Pathoschild** [comment]
Done. 42797f305f36f3e8f486e9be68c8c68a16854558 is what broke the shipping bin. The idea was that instead of pressing the "organize" button to change shipping bin mode, the dropdown would just show a separate entry for each mode. Looks like I accidentally set both to `ShippingBinMode.MobileStore` though.

**Comment by Pathoschild** [comment]
The upcoming SMAPI 3.4 will let Virtual Keyboard send actual input to the game/mods, instead of faking the SMAPI event. The method is internal, but it can be used via reflection:
```cs
SButton button = ...; // the button code to send

var input = helper.Reflection.GetField<object>(typeof(Game1), "input").GetValue();
input
   .GetType()
   .GetMethod("OverrideButton")
   .Invoke(input, new object[] { button, true });
```

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Thanks for the pull request! Merged into `develop` for the upcoming Chests Anywhere 1.18. I'll add a note that using a non-physical key on Android will need SMAPI 3.4.

**Pull request closed without merging**
