### PR TITLE
Update Russian translations for DataLayers

### PR DESCRIPTION
**Pull request by VengelmBjorn**
Translated new lines and few changes in old translation.

### CODE REVIEW

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
@VengelmBjorn Thanks for the help! Added to the next Data Layers update.

There's one new translation in the next version shown in the tillable layer when a tile is tilled, but not planted yet. If you'd like to translate it too, feel free to reply here with the text or send a new PR.
```js
"tillable.tilled": "Tilled", // TODO
```

**Comment by VengelmBjorn** [comment]
If i get it right it will be
"tillable.tilled": "Вспахано",

**Comment by VengelmBjorn** [comment]
It will be
"tillable.tilled": "Уже вспахано",

**Comment by Pathoschild** [comment]
Thanks again!

**Pull request merged**
