### PR TITLE
[Fast Animations] More Fast Animations

### PR DESCRIPTION
**Pull request by weizinai**
Speed up the chest-open animation.
Speed up the item-holdup animation.

### CODE REVIEW

**Comment by weizinai** [comment]
The temporary sprite issue is not solved.

**Comment by Pathoschild** [comment]
Hi! What do you mean by the temporary sprite issue?

**Comment by weizinai** [comment]
I solved this problem based on HarvestHandler. At first, I only sped up the player's animation, which caused there to be temporary 
sprite of items stuck on the map.

**Comment by weizinai** [comment]
But now there's another problem, the animation for holding up the item only lasts 3000 milliseconds, but pauses the player for 4000 milliseconds, which results in 1000 milliseconds before the player can move after the animation ends.

**Comment by Pathoschild** [comment]
I suggest submitting a separate PR for each feature. That way we can release the ones that are ready, even if one of them is still in progress.

**Comment by weizinai** [comment]
I have submitted a separate PR for each feature. I apologize, this is my first PR submission.

**Pull request closed without merging**
