### PR TITLE
[Lookup Anything] Revamp recipe layout, add reverse recipes

### LINKED ISSUE #562: [Lookup Anything] add reverse recipe lookup
Looking up an item should show any recipes that produce it.

Proposed in the [Nexus comments for Lookup Anything](https://www.nexusmods.com/stardewvalley/mods/541/?tab=posts&jump_to_comment=83892688) (2020-08-04).

### LINKED ISSUE #567: [Lookup Anything] Improve recipe UI for custom recipes
Lookup Anything shows recipes on one line. That works fine for vanilla recipes, but breaks down with the larger recipes added by some mods:

### PR DESCRIPTION
**Pull request by cofiem**
My first go at modding Stardew Valley.

Aims to address the Lookup Anything issue [add reverse recipe lookup](https://github.com/Pathoschild/StardewMods/issues/562).

"Looking up an item should show any recipes that produce it."

New class 'RecipesForOutputItemField' is based on 'RecipesForMachineField'.

Work in progress.
Closes #562.

### CODE REVIEW

**Review by Pathoschild — CHANGES_REQUESTED** [review]
Thanks for the pull request!

The new field duplicates a lot of code from `RecipesForIngredientField` though; we should refactor as needed to avoid that. For example, we could have one `ItemRecipeField` with two factory methods (`ItemRecipeField.ForIngredient(...)` and `ItemRecipeField.ForOutput(...)`).

**Comment by cofiem** [comment]
Most of the recipes I've checked look good. There might be a few missing, but that can be improved.

I have found a couple of oddities, where I don't know what's going on.
I'm guessing there's a mismatch of item IDs or an overlap or something like that...

The Leek info window shows the crafting recipe for the Recycling Machine:
image

Joja Cola shows the crafting recipe for the Deluxe Scarecrow:
image

**Comment by Pathoschild** [comment]
Yep, those are just ID collisions since you don't check the item type; Leek is object # 20 and Recycling Machine is bigcraftable # 20. You can solve that by comparing the `RecipeModel.OutputItemType` property with `item.GetItemType()` (an extension in the `Pathoschild.Stardew.Common` namespace).

**Comment by Pathoschild** [comment]
(I renamed the original field in the `develop` branch and rebased your changes, so we keep the commit history for that file. You'll need to reset your local branch to the latest one on the server.)

**Comment by Pathoschild** [comment]
Sorry for the confusion, I only meant we should merge the fields that are rendering the same style; `RecipesForIngredientField` and `RecipesForMachineField` have very different rendering, so it made sense to keep it separate.

But since we're halfway there anyway, we could go further and make recipe rendering consistent across all fields. For example, when looking up an item:

<table>
<tr>
<th>current format</th>
<th></th>
<th>unified format</th>
</tr>
<tr>
<td>

```
Crafting:
   Barrel Brazier (needs 1)
   Bee House (needs 8)
   Bomb (needs 1)
   …

Furnace:
   Copper Bar (needs 1)
   Gold Bar (needs 1)
   …
```

</td>
<td>→</td>
<td>

```
Crafting:
   Barrel Brazier: Coal + Wood x50 + Solar Essence
   Bee House: Coal x8 + Wood x40 + Iron Bar + Maple Syrup
   Bomb: Coal + Iron Ore x4
   …

Furnace:
  Copper Bar: Coal + Copper Ore x5
  Gold Bar: Coal + Gold Ore x5
  …
```

</td>
</tr>
</table>

That should also simplify the logic in the unified `ItemRecipesField`, since it won't need to handle two different rendering styles anymore.

**Comment by cofiem** [comment]
All good. Sounds like a good idea to make one recipe display format. I'll give that a go.

**Comment by cofiem** [comment]
Some examples of the new 'unified' format:
example1
example2
example3

**Comment by cofiem** [comment]
Ready for review.
This change might satisfy #567 as well.

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Thanks a lot! Merged into `develop` (with a few changes) for the upcoming Lookup Anything 1.33.

**Pull request merged**
