### PR TITLE
Add Vietnamese translations for Lookup Anything

### PR DESCRIPTION
**Pull request by bl205vn**

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks! I see this comment in the file:
```js
//trans by dragonly and CuongNguyen
```

I'll need permission from each translator who worked on that file to release the translations under [this repo's MIT license](https://github.com/Pathoschild/StardewMods/blob/develop/LICENSE). A reply from each translator here is ideal, but I can verify a different way if needed.

**Comment by cuongnguyen0903** [comment]
> Thanks! I see this comment in the file:
> 
> ```js
> //trans by dragonly and CuongNguyen
> ```
> 
> I'll need permission from each translator who worked on that file to release the translations under [this repo's MIT license](https://github.com/Pathoschild/StardewMods/blob/develop/LICENSE). A reply from each translator here is ideal, but I can verify a different way if needed.

Yes, I'm the one who translated that mod

**Comment by Pathoschild** [comment]
@bl205vn @cuongnguyen0903 Thanks! Who is dragonly in the comment?

**Comment by bl205vn** [comment]
Dragonly has agreed, but they're not proficient in using GitHub so they won't comment here. [You can verify it here](https://www.nexusmods.com/stardewvalley/mods/17050?tab=posts&jump_to_comment=140514868), but it's not in English.

**Comment by Pathoschild** [comment]
Based on Dragonly's mod description, those translations were [originally created by HoangAries / kaharasimaru](https://www.nexusmods.com/stardewvalley/mods/10665):
> Do bản [Lookup Anything vietnam translation](https://www.nexusmods.com/stardewvalley/mods/10665) này đã cũ nên mình dịch rồi tổng hợp lại trên bản mới
> Dịch được khoảng 90% .
> Nguồn tham khảo: mod [Lookup Anything vietnam translation](https://www.nexusmods.com/stardewvalley/mods/10665) và chị google.

 So unfortunately we'll need permission from them too. Since Lookup Anything has an open-source license, everyone who created the translations needs to release their contributions under that license (since they have a copyright on their changes).

**Comment by bl205vn** [comment]
I am cancelling the pull request because I cannot reach the previous translator.

**Comment by Pathoschild** [comment]
Alright. New Vietnamese translations are always welcome if someone wants to re-translate the mod (without referencing those). Thanks again for the PR!

**Pull request closed without merging**
