### PR TITLE
Update Chinese translations for Lookup Anything

### PR DESCRIPTION
**Pull request by asqwedcxz741**
Add and modify Chinese translation for lookupanything.

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks! 

It looks like you missed some (feel free to ask if they're unclear):
```js
    "location.unknown-fish-area": "{{locationName}} (fishing area {{id}})",
```
```js
    "item.undiscovered-gift-taste": "{{count}} unrevealed villagers", 
    "item.undiscovered-gift-taste-appended": ", and {{count}} unrevealed villagers",
```

For these ones, "ix props" means _index properties_ (game properties that are linked to the tile type) and "props" means _properties_ (game properties that are linked to that specific tile position). Example properties are `Type Grass` or `Action Warp`.
```js
    "tile.index-property": "{{layerName}}: ix props: {{propertyName}}",//TODO
    "tile.tile-property": "{{layerName}}: props: {{propertyName}}",//TODO
```

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Merged into `develop` for the next update. Feel free to submit a new pull request if you want to add the missing translations. Thanks again!

**Comment by asqwedcxz741** [comment]
> 谢谢！
> 
> 好像您错过了一些（随意询问他们是否不清楚）：
> 
> ```js
>     “ location.unknown-fish-area ”： “ {{locationName}}（捕鱼区{{id}}）”，
> ```
> 
> ```js
>     “ item.undiscovered礼味”： “ {{count}}个未揭露的村民”， 
>      “ item.undiscovered礼味补写”： “和{{count}}个未揭露的村民”，
> ```
> 
> 对于这些，“ ix props”表示_索引属性_（链接到图块类型的游戏属性），“ props”表示_属性_（链接到该特定图块位置的游戏属性）。示例属性为`Type Grass`或`Action Warp`。
> 
> ```js
>     “ tile.index-property ”： “ {{layerName}}：ix个道具：{{propertyName}} ”， // TODO 
>     “ tile.tile-property ”： “ {{layerName}}：道具：{{propertyName}} “， // TODO
> ```

Hello! In fact, I missed them because I don't know how to translate them yet. It seems that I didn't play with the corresponding content.

**Comment by asqwedcxz741** [comment]
Thank you again for your hard work! If I know the correct Chinese translation, I will submit it again.

**Pull request merged**
